[package]
name = "parsey-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
pdf-extract = "0.7.2"
prost = "0.12.3"
tokio = { version = "1.27.0", features = ["full"] }
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
